language: scala

# Cassandra on Travis seems outdated.
# services:
#  - cassandra

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://archive.apache.org/dist/cassandra/3.3/apache-cassandra-3.3-bin.tar.gz && tar -xvzf apache-cassandra-3.3-bin.tar.gz
  - export JVM_OPTS_OLD=$JVM_OPTS
  - unset JVM_OPTS
  - sudo sh ./apache-cassandra-3.3/bin/cassandra -R
  - export JVM_OPTS=$JVM_OPTS_OLD
  - sleep 20